version: '2.1'

networks:
  spring-net:

services:
  mysql:
    #image: mysql:5.7
    build: ./mysql  # 指定 Dockerfile 所在路径
    container_name: mysql57
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    networks:
      - spring-net